POST https://ticketing.dev/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"password"
}

###

POST https://ticketing.dev/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email":"test@test.com",
  "password":"password"
}

###

GET https://ticketing.dev/api/users/currentuser HTTP/1.1
Content-Type: application/json

###
POST https://ticketing.dev/api/users/signout HTTP/1.1
Content-Type: application/json
